const XENOS = [
  {
    "id": "CMXenoBurrower",
    "name": "Бурильщик",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/burrower.yml",
    "xenoArmor": 25.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.4
  },
  {
    "id": "CMXenoCarrier",
    "name": "Носитель",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/carrier.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.4
  },
  {
    "id": "CMXenoDefender",
    "name": "Защитник",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/defender.yml",
    "xenoArmor": 35.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.45
  },
  {
    "id": "CMXenoDefenderSteelcrest",
    "name": "Защитник",
    "strain": "Стальной гребень",
    "file": "_RMC14/Entities/Mobs/Xeno/defender.yml",
    "xenoArmor": 35.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.45
  },
  {
    "id": "CMXenoDrone",
    "name": "Дрон",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/drone.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 15.0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 15.0,
    "hitboxRadius": 0.4
  },
  {
    "id": "CMXenoDroneGardener",
    "name": "Дрон",
    "strain": "Садовник",
    "file": "_RMC14/Entities/Mobs/Xeno/drone.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 15.0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 15.0,
    "hitboxRadius": 0.4
  },
  {
    "id": "CMXenoDroneHealer",
    "name": "Дрон",
    "strain": "Целитель",
    "file": "_RMC14/Entities/Mobs/Xeno/drone.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 15.0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 15.0,
    "hitboxRadius": 0.4
  },
  {
    "id": "CMXenoHivelord",
    "name": "Повелитель улья",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/hivelord.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.4
  },
  {
    "id": "CMXenoHivelordDesigner",
    "name": "Повелитель улья",
    "strain": "Дизайнер",
    "file": "_RMC14/Entities/Mobs/Xeno/hivelord.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.4
  },
  {
    "id": "CMXenoHivelordResinWhisperer",
    "name": "Повелитель улья",
    "strain": "Смоляной Шептун",
    "file": "_RMC14/Entities/Mobs/Xeno/hivelord.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.4
  },
  {
    "id": "CMXenoLarva",
    "name": "Личинка",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/larva.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Small",
    "sizeEvasionMod": 10,
    "evasionModified": 10,
    "hitboxRadius": 0.25
  },
  {
    "id": "CMXenoLesserDrone",
    "name": "Малый дрон",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/lesser_drone.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 10.0,
    "size": "VerySmallXeno",
    "sizeEvasionMod": 0,
    "evasionModified": 10.0,
    "hitboxRadius": 0.4
  },
  {
    "id": "CMXenoLurker",
    "name": "Охотник",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/lurker.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.4
  },
  {
    "id": "CMXenoParasite",
    "name": "Лицехват",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/parasite.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Small",
    "sizeEvasionMod": 10,
    "evasionModified": 10,
    "hitboxRadius": 0.25
  },
  {
    "id": "CMXenoPraetorian",
    "name": "Преторианец",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/praetorian.yml",
    "xenoArmor": 25.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.45
  },
  {
    "id": "CMXenoQueen",
    "name": "Королева",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/queen.yml",
    "xenoArmor": 25.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Immobile",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.52
  },
  {
    "id": "CMXenoRavager",
    "name": "Разрушитель",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/ravager.yml",
    "xenoArmor": 25.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.5
  },
  {
    "id": "CMXenoRunner",
    "name": "Бегун",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/runner.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "SmallXeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.4
  },
  {
    "id": "CMXenoSentinel",
    "name": "Страж",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/sentinel.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.4
  },
  {
    "id": "CMXenoSpitter",
    "name": "Плеватель",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/spitter.yml",
    "xenoArmor": 15.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.4
  },
  {
    "id": "CMXenoWarrior",
    "name": "Воин",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/warrior.yml",
    "xenoArmor": 20.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.4
  },
  {
    "id": "RMCXenoBoiler",
    "name": "Бойлер",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/boiler.yml",
    "xenoArmor": 20.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.45
  },
  {
    "id": "RMCXenoBoilerSapper",
    "name": "Бойлер",
    "strain": "Сапёр",
    "file": "_RMC14/Entities/Mobs/Xeno/boiler.yml",
    "xenoArmor": 0.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.45
  },
  {
    "id": "RMCXenoCarrierEggsac",
    "name": "Носитель",
    "strain": "Кокон",
    "file": "_RMC14/Entities/Mobs/Xeno/carrier.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.4
  },
  {
    "id": "RMCXenoCrusher",
    "name": "Крушитель",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/crusher.yml",
    "xenoArmor": 30.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Immobile",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.4
  },
  {
    "id": "RMCXenoCrusherCharger",
    "name": "Крушитель",
    "strain": "Таран",
    "file": "_RMC14/Entities/Mobs/Xeno/crusher.yml",
    "xenoArmor": 20.0,
    "frontalArmor": 30.0,
    "sideArmor": 15.0,
    "evasion": 0,
    "size": "Immobile",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.4
  },
  {
    "id": "RMCXenoKing",
    "name": "Король",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/king.yml",
    "xenoArmor": 45.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Immobile",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.52
  },
  {
    "id": "RMCXenoLurkerVampire",
    "name": "Охотник",
    "strain": "Вампир",
    "file": "_RMC14/Entities/Mobs/Xeno/lurker.yml",
    "xenoArmor": 20.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.4
  },
  {
    "id": "RMCXenoParasiteWatcher",
    "name": "Лицехват",
    "strain": "Наблюдатель",
    "file": "_RMC14/Entities/Mobs/Xeno/parasite.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Small",
    "sizeEvasionMod": 10,
    "evasionModified": 10,
    "hitboxRadius": 0.25
  },
  {
    "id": "RMCXenoPraetorianDancer",
    "name": "Преторианец",
    "strain": "Танцор",
    "file": "_RMC14/Entities/Mobs/Xeno/praetorian.yml",
    "xenoArmor": 20.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.45
  },
  {
    "id": "RMCXenoPraetorianOppressor",
    "name": "Преторианец",
    "strain": "Угнетатель",
    "file": "_RMC14/Entities/Mobs/Xeno/praetorian.yml",
    "xenoArmor": 25.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.45
  },
  {
    "id": "RMCXenoPraetorianValkyrie",
    "name": "Преторианец",
    "strain": "Валькирия",
    "file": "_RMC14/Entities/Mobs/Xeno/praetorian.yml",
    "xenoArmor": 35.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.45
  },
  {
    "id": "RMCXenoPraetorianVanguard",
    "name": "Преторианец",
    "strain": "Авангард",
    "file": "_RMC14/Entities/Mobs/Xeno/praetorian.yml",
    "xenoArmor": 25.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.45
  },
  {
    "id": "RMCXenoRavagerBerserker",
    "name": "Разрушитель",
    "strain": "Берсерк",
    "file": "_RMC14/Entities/Mobs/Xeno/ravager.yml",
    "xenoArmor": 30.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.5
  },
  {
    "id": "RMCXenoRavagerHedgehog",
    "name": "Разрушитель",
    "strain": "Ёж",
    "file": "_RMC14/Entities/Mobs/Xeno/ravager.yml",
    "xenoArmor": 25.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.5
  },
  {
    "id": "RMCXenoRunnerAcider",
    "name": "Бегун",
    "strain": "Окислитель",
    "file": "_RMC14/Entities/Mobs/Xeno/runner.yml",
    "xenoArmor": 15.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "SmallXeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.4
  },
  {
    "id": "STXenoDespoiler",
    "name": "Дисбойлер",
    "strain": null,
    "file": "_Stories/Entities/Mobs/Xeno/despoiler.yml",
    "xenoArmor": 25.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.45
  },
  {
    "id": "STXenoWarriorBoxer",
    "name": "Воин",
    "strain": "Боксёр",
    "file": "_Stories/Entities/Mobs/Xeno/warrior.yml",
    "xenoArmor": 25.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.4
  },
  {
    "id": "STXenoWarriorBulwark",
    "name": "Воин",
    "strain": "Бастион",
    "file": "_Stories/Entities/Mobs/Xeno/warrior.yml",
    "xenoArmor": 30.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.4
  }
];
