const XENOS = [
  {
    "id": "CMXenoBurrower",
    "name": "Бурильщик",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/burrower.yml",
    "xenoArmor": 25.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.4,
    "armorAbilities": []
  },
  {
    "id": "CMXenoCarrier",
    "name": "Носитель",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/carrier.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.4,
    "armorAbilities": []
  },
  {
    "id": "CMXenoDefender",
    "name": "Защитник",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/defender.yml",
    "xenoArmor": 35.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.45,
    "armorAbilities": [
      {
        "id": "crest",
        "name": "Защита гребня",
        "kind": "toggle",
        "xenoArmor": 5,
        "frontalArmor": 0,
        "sideArmor": 0,
        "exclusiveWith": [
          "fortify"
        ]
      },
      {
        "id": "fortify",
        "name": "Укрепление",
        "kind": "toggle",
        "xenoArmor": 30,
        "frontalArmor": 5,
        "sideArmor": 0,
        "exclusiveWith": [
          "crest"
        ]
      }
    ]
  },
  {
    "id": "CMXenoDefenderSteelcrest",
    "name": "Защитник",
    "strain": "Стальной гребень",
    "file": "_RMC14/Entities/Mobs/Xeno/defender.yml",
    "xenoArmor": 35.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.45,
    "armorAbilities": [
      {
        "id": "crest",
        "name": "Защита гребня",
        "kind": "toggle",
        "xenoArmor": 5,
        "frontalArmor": 0,
        "sideArmor": 0,
        "exclusiveWith": [
          "fortify"
        ]
      },
      {
        "id": "fortify",
        "name": "Укрепление",
        "kind": "toggle",
        "xenoArmor": 10.0,
        "frontalArmor": 15.0,
        "sideArmor": 0,
        "exclusiveWith": [
          "crest"
        ]
      }
    ]
  },
  {
    "id": "CMXenoDrone",
    "name": "Дрон",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/drone.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 15.0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 15.0,
    "hitboxRadius": 0.4,
    "armorAbilities": []
  },
  {
    "id": "CMXenoDroneGardener",
    "name": "Дрон",
    "strain": "Садовник",
    "file": "_RMC14/Entities/Mobs/Xeno/drone.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 15.0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 15.0,
    "hitboxRadius": 0.4,
    "armorAbilities": []
  },
  {
    "id": "CMXenoDroneHealer",
    "name": "Дрон",
    "strain": "Целитель",
    "file": "_RMC14/Entities/Mobs/Xeno/drone.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 15.0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 15.0,
    "hitboxRadius": 0.4,
    "armorAbilities": []
  },
  {
    "id": "CMXenoHivelord",
    "name": "Повелитель улья",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/hivelord.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.4,
    "armorAbilities": []
  },
  {
    "id": "CMXenoHivelordDesigner",
    "name": "Повелитель улья",
    "strain": "Дизайнер",
    "file": "_RMC14/Entities/Mobs/Xeno/hivelord.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.4,
    "armorAbilities": []
  },
  {
    "id": "CMXenoHivelordResinWhisperer",
    "name": "Повелитель улья",
    "strain": "Смоляной Шептун",
    "file": "_RMC14/Entities/Mobs/Xeno/hivelord.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.4,
    "armorAbilities": []
  },
  {
    "id": "CMXenoLarva",
    "name": "Личинка",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/larva.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Small",
    "sizeEvasionMod": 10,
    "evasionModified": 10,
    "hitboxRadius": 0.25,
    "armorAbilities": []
  },
  {
    "id": "CMXenoLesserDrone",
    "name": "Малый дрон",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/lesser_drone.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 10.0,
    "size": "VerySmallXeno",
    "sizeEvasionMod": 0,
    "evasionModified": 10.0,
    "hitboxRadius": 0.4,
    "armorAbilities": []
  },
  {
    "id": "CMXenoLurker",
    "name": "Охотник",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/lurker.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.4,
    "armorAbilities": []
  },
  {
    "id": "CMXenoParasite",
    "name": "Лицехват",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/parasite.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Small",
    "sizeEvasionMod": 10,
    "evasionModified": 10,
    "hitboxRadius": 0.25,
    "armorAbilities": []
  },
  {
    "id": "CMXenoPraetorian",
    "name": "Преторианец",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/praetorian.yml",
    "xenoArmor": 25.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.45,
    "armorAbilities": []
  },
  {
    "id": "CMXenoQueen",
    "name": "Королева",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/queen.yml",
    "xenoArmor": 25.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Immobile",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.52,
    "armorAbilities": []
  },
  {
    "id": "CMXenoRavager",
    "name": "Разрушитель",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/ravager.yml",
    "xenoArmor": 25.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.5,
    "armorAbilities": []
  },
  {
    "id": "CMXenoRunner",
    "name": "Бегун",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/runner.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "SmallXeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.4,
    "armorAbilities": []
  },
  {
    "id": "CMXenoSentinel",
    "name": "Страж",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/sentinel.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.4,
    "armorAbilities": []
  },
  {
    "id": "CMXenoSpitter",
    "name": "Плеватель",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/spitter.yml",
    "xenoArmor": 15.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.4,
    "armorAbilities": [
      {
        "id": "chargeSpit",
        "name": "Заряженный плевок",
        "kind": "toggle",
        "xenoArmor": 5,
        "frontalArmor": 0,
        "sideArmor": 0
      }
    ]
  },
  {
    "id": "CMXenoWarrior",
    "name": "Воин",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/warrior.yml",
    "xenoArmor": 20.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.4,
    "armorAbilities": []
  },
  {
    "id": "RMCXenoBoiler",
    "name": "Бойлер",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/boiler.yml",
    "xenoArmor": 20.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.45,
    "armorAbilities": []
  },
  {
    "id": "RMCXenoBoilerSapper",
    "name": "Бойлер",
    "strain": "Сапёр",
    "file": "_RMC14/Entities/Mobs/Xeno/boiler.yml",
    "xenoArmor": 0.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.45,
    "armorAbilities": []
  },
  {
    "id": "RMCXenoCarrierEggsac",
    "name": "Носитель",
    "strain": "Кокон",
    "file": "_RMC14/Entities/Mobs/Xeno/carrier.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.4,
    "armorAbilities": []
  },
  {
    "id": "RMCXenoCrusher",
    "name": "Крушитель",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/crusher.yml",
    "xenoArmor": 30.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Immobile",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.4,
    "armorAbilities": []
  },
  {
    "id": "RMCXenoCrusherCharger",
    "name": "Крушитель",
    "strain": "Таран",
    "file": "_RMC14/Entities/Mobs/Xeno/crusher.yml",
    "xenoArmor": 20.0,
    "frontalArmor": 30.0,
    "sideArmor": 15.0,
    "evasion": 0,
    "size": "Immobile",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.4,
    "armorAbilities": []
  },
  {
    "id": "RMCXenoKing",
    "name": "Король",
    "strain": null,
    "file": "_RMC14/Entities/Mobs/Xeno/king.yml",
    "xenoArmor": 45.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Immobile",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.52,
    "armorAbilities": []
  },
  {
    "id": "RMCXenoLurkerVampire",
    "name": "Охотник",
    "strain": "Вампир",
    "file": "_RMC14/Entities/Mobs/Xeno/lurker.yml",
    "xenoArmor": 20.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.4,
    "armorAbilities": []
  },
  {
    "id": "RMCXenoParasiteWatcher",
    "name": "Лицехват",
    "strain": "Наблюдатель",
    "file": "_RMC14/Entities/Mobs/Xeno/parasite.yml",
    "xenoArmor": 0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Small",
    "sizeEvasionMod": 10,
    "evasionModified": 10,
    "hitboxRadius": 0.25,
    "armorAbilities": []
  },
  {
    "id": "RMCXenoPraetorianDancer",
    "name": "Преторианец",
    "strain": "Танцор",
    "file": "_RMC14/Entities/Mobs/Xeno/praetorian.yml",
    "xenoArmor": 20.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.45,
    "armorAbilities": []
  },
  {
    "id": "RMCXenoPraetorianOppressor",
    "name": "Преторианец",
    "strain": "Угнетатель",
    "file": "_RMC14/Entities/Mobs/Xeno/praetorian.yml",
    "xenoArmor": 25.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.45,
    "armorAbilities": []
  },
  {
    "id": "RMCXenoPraetorianValkyrie",
    "name": "Преторианец",
    "strain": "Валькирия",
    "file": "_RMC14/Entities/Mobs/Xeno/praetorian.yml",
    "xenoArmor": 35.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.45,
    "armorAbilities": [
      {
        "id": "tantrum",
        "name": "Вспышка ярости",
        "kind": "toggle",
        "xenoArmor": 10,
        "frontalArmor": 0,
        "sideArmor": 0
      }
    ]
  },
  {
    "id": "RMCXenoPraetorianVanguard",
    "name": "Преторианец",
    "strain": "Авангард",
    "file": "_RMC14/Entities/Mobs/Xeno/praetorian.yml",
    "xenoArmor": 25.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.45,
    "armorAbilities": []
  },
  {
    "id": "RMCXenoRavagerBerserker",
    "name": "Разрушитель",
    "strain": "Берсерк",
    "file": "_RMC14/Entities/Mobs/Xeno/ravager.yml",
    "xenoArmor": 30.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.5,
    "armorAbilities": [
      {
        "id": "rage",
        "name": "Ярость",
        "kind": "counter",
        "per": 3,
        "step": 1,
        "max": 5,
        "unit": "стаков"
      }
    ]
  },
  {
    "id": "RMCXenoRavagerHedgehog",
    "name": "Разрушитель",
    "strain": "Ёж",
    "file": "_RMC14/Entities/Mobs/Xeno/ravager.yml",
    "xenoArmor": 25.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.5,
    "armorAbilities": [
      {
        "id": "shards",
        "name": "Осколки",
        "kind": "counter",
        "per": 2.5,
        "step": 50,
        "max": 300.0,
        "unit": "осколков"
      }
    ]
  },
  {
    "id": "RMCXenoRunnerAcider",
    "name": "Бегун",
    "strain": "Окислитель",
    "file": "_RMC14/Entities/Mobs/Xeno/runner.yml",
    "xenoArmor": 15.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "SmallXeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.4,
    "armorAbilities": []
  },
  {
    "id": "STXenoDespoiler",
    "name": "Дисбойлер",
    "strain": null,
    "file": "_Stories/Entities/Mobs/Xeno/despoiler.yml",
    "xenoArmor": 25.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.45,
    "armorAbilities": []
  },
  {
    "id": "STXenoWarriorBoxer",
    "name": "Воин",
    "strain": "Боксёр",
    "file": "_Stories/Entities/Mobs/Xeno/warrior.yml",
    "xenoArmor": 25.0,
    "frontalArmor": 0,
    "sideArmor": 0,
    "evasion": 0,
    "size": "Big",
    "sizeEvasionMod": -10,
    "evasionModified": -10,
    "hitboxRadius": 0.4,
    "armorAbilities": []
  },
  {
    "id": "STXenoWarriorBulwark",
    "name": "Воин",
    "strain": "Бастион",
    "file": "_Stories/Entities/Mobs/Xeno/warrior.yml",
    "xenoArmor": 30.0,
    "frontalArmor": 10,
    "sideArmor": 10,
    "evasion": 0,
    "size": "Xeno",
    "sizeEvasionMod": 0,
    "evasionModified": 0,
    "hitboxRadius": 0.4,
    "passiveArmor": {
      "frontal": 10,
      "side": 10
    },
    "armorAbilities": [
      {
        "id": "encasedPlates",
        "name": "Закованные Пластины",
        "kind": "toggle",
        "xenoArmor": 0,
        "frontalArmor": 10,
        "sideArmor": -10
      }
    ]
  }
];
